version: '3'
services:
  app:
    container_name: tigernodeandspace-client
    image: fabriceesope/tigernodeandspace-client
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - tigernodeandspace
  tigernodeandspace:
    image: fabriceesope/tigernodeandspace

